name: nlp
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.9
  - black
  - ipython
  - notebook
  - ipykernel
  - pytorch=1.10.2
  - tqdm
  - numpy
  - pandas
  - pytest
  - tensorboard
  - pyright
  - wandb
  - python-dotenv
  - nltk
  - transformers
  - datasets
  - scikit-learn
  - spacy
  - imbalanced-learn
  - swifter
  - huggingface_hub
  - pytorch-lightning
  - pip
  - pip:
      - URLExtract
      - emoji>=2.0.0
      - autocorrect
      - spello
      - joblib
      - pydeps

prefix: /usr/local/anaconda3/envs/nlp
